# Generated by Django 6.0.5 on 2026-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='architecture_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lines_of_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='performance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='production_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='security_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
