# Generated by Django 6.0.5 on 2026-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysis_architecture_score_analysis_files_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='response_time',
            field=models.FloatField(default=0),
        ),
    ]
