# Generated by Django 6.0.5 on 2026-06-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysis_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
