# Generated by Django 6.0.5 on 2026-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_analysis_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
